-- Table: public.authenticators

-- DROP TABLE public.authenticators;

CREATE TABLE public.authenticators
(
    relay text COLLATE pg_catalog."default" NOT NULL,
    round bigint NOT NULL,
    auth text COLLATE pg_catalog."default" NOT NULL
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public.authenticators
    OWNER to tsachi;

    -- Table: public.authenticators_distribution

-- DROP TABLE public.authenticators_distribution;

CREATE TABLE public.authenticators_distribution
(
    round bigint NOT NULL,
    auth text COLLATE pg_catalog."default" NOT NULL,
    dist real NOT NULL
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public.authenticators_distribution
    OWNER to tsachi;

    -- Table: public.rounds

-- DROP TABLE public.rounds;

CREATE TABLE public.rounds
(
    round bigint NOT NULL,
    relay_count bigint NOT NULL,
    auth_count bigint NOT NULL
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public.rounds
    OWNER to tsachi;

-- Table: public.roundrelays

-- DROP TABLE public.roundrelays;

CREATE TABLE public.roundrelays
(
    round bigint NOT NULL,
    relay text COLLATE pg_catalog."default" NOT NULL,
    auth_count bigint NOT NULL,
    CONSTRAINT roundelay_pkey PRIMARY KEY (round, relay)
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public.roundrelays
    OWNER to tsachi;


CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE ,
    passwordHash VARCHAR(255) NOT NULL
);

CREATE TABLE userTokens (
  series varchar(50) NOT NULL,
  userId int DEFAULT NULL,
  challenge varchar(50) DEFAULT NULL,
  expires bigint DEFAULT NULL,
  PRIMARY KEY (series)
);

CREATE TABLE admins (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE ,
    passwordHash VARCHAR(255) NOT NULL
);